"""add Department

Revision ID: 047733fa6f80
Revises: fd192aa194ec
Create Date: 2024-07-05 10:52:56.188407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047733fa6f80'
down_revision = 'fd192aa194ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###